name: social-rotation-frontend
static_sites:
- name: frontend
  source_dir: /
  github:
    repo: BrandonSocialRotation/social-rotation-frontend
    branch: main
  build_command: npm ci --legacy-peer-deps && npm run build
  output_dir: dist
  environment_slug: node-js
  catchall_document: index.html
  envs:
  - key: VITE_API_BASE_URL
    value: https://new-social-rotation-backend-qzyk8.ondigitalocean.app/api/v1
