name: social-rotation-frontend
static_sites:
- name: frontend
  source_dir: /
  github:
    repo: BrandonSocialRotation/social-rotation-frontend
    branch: main
  build_command: npm ci && npm run build
  output_dir: dist
  catchall_document: index.html
  routes:
  - path: /
  - path: /dashboard
  - path: /login
  - path: /register
  - path: /buckets
  - path: /schedule
  - path: /profile
  - path: /sub-accounts
  - path: /rss-feeds
  - path: /terms-of-service
  - path: /privacy-policy
  - path: /oauth/callback
  envs:
  - key: VITE_API_BASE_URL
    value: https://new-social-rotation-backend-qzyk8.ondigitalocean.app/api/v1
